# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.hostname = 'damn-vulnerable-restaurant-api-game'

  config.vm.provider "hyperv" do |hyperv|
    hyperv.vmname = "damn-vulnerable-restaurant-api-game"
    hyperv.cpus = "2"
    hyperv.memory = "2048"
    hyperv.maxmemory = "2048"
    hyperv.enable_enhanced_session_mode = true
  end

  config.vm.provision :shell, path: "bootstrap.sh"

  config.vm.network "public_network", bridge: "External Switch"
end
