# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"

  config.vm.hostname = 'kali'
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provider "hyperv" do |hyperv|
    hyperv.vmname = "Kali"
    hyperv.cpus = "2"
    hyperv.memory = "2048"
    hyperv.maxmemory = "2048"
    hyperv.enable_enhanced_session_mode = true
  end

  config.vm.network "public_network", bridge: "External Switch"

  # config.vm.provision "shell", inline: <<-SHELL
  # SHELL

  # config.ssh.username = "ubuntu"
  # config.ssh.private_key_path = "C:\\Users\\admin\\.ssh\\id_ed25519"
  # config.ssh.forward_agent = true
end
