# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.hostname = 'ubuntu'

  config.vm.provider "hyperv" do |hyperv|
    hyperv.vmname = "Ubuntu"
    hyperv.cpus = "2"
    hyperv.memory = "2048"
    hyperv.maxmemory = "4096"
    hyperv.enable_enhanced_session_mode = true
  end

  config.vm.network "public_network", bridge: "External Switch"

  config.vm.provision "shell", inline: <<-SHELL
    # Add Docker's official GPG key:
    apt-get update
    apt-get install ca-certificates curl gnupg
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg

    # Add the repository to Apt sources:
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update

    apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  SHELL

  # config.ssh.username = "ubuntu"
  # config.ssh.private_key_path = "C:\\Users\\admin\\.ssh\\id_ed25519"
  # config.ssh.forward_agent = true
end
