# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.hostname = 'ubuntu'

  config.vm.provider "hyperv" do |hyperv|
    hyperv.vmname = "Ubuntu"
    hyperv.cpus = "4"
    hyperv.memory = "4096"
    hyperv.maxmemory = "4096"
    hyperv.enable_enhanced_session_mode = true
  end

  config.vm.network "public_network", bridge: "External Switch"

  config.vm.provision "shell", inline: <<-SHELL
    export KUBERNETES_VERSION=v1.29
    export CRIO_VERSION=v1.29

    apt-get update
    apt-get install -y software-properties-common curl

    curl -fsSL https://pkgs.k8s.io/core:/stable:/$KUBERNETES_VERSION/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/$KUBERNETES_VERSION/deb/ /" |tee /etc/apt/sources.list.d/kubernetes.list

    curl -fsSL https://pkgs.k8s.io/addons:/cri-o:/stable:/$CRIO_VERSION/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/cri-o-apt-keyring.gpg
    echo "deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://pkgs.k8s.io/addons:/cri-o:/stable:/$CRIO_VERSION/deb/ /" | tee /etc/apt/sources.list.d/cri-o.list

    apt-get update
    apt-get install -y socat cri-o kubelet kubeadm kubectl
    apt-mark hold cri-o kubelet kubeadm kubectl

    systemctl enable crio
    systemctl start crio

    swapoff -a
    sed -i '/\tswap\t/d' /etc/fstab

    cat << EOF | tee /etc/modules-load.d/cri-o.conf
br_netfilter
EOF

    modprobe br_netfilter

    cat << EOF | tee /etc/crio/crio.conf.d/02-cgroup-manager.conf
[crio.runtime]
conmon_cgroup = "pod"
cgroup_manager = "cgroupfs"
EOF

    cat << EOF | tee /etc/sysctl.d/kubernetes.conf
net.ipv4.ip_forward = 1
EOF

    sysctl --system

    systemctl stop ufw
    systemctl disable ufw

    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    mv kubectl /usr/local/bin/
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    curl -L -O https://github.com/derailed/k9s/releases/download/v0.32.5/k9s_Linux_amd64.tar.gz
    tar -xzf k9s_Linux_amd64.tar.gz k9s
    mv k9s /usr/local/bin/
    rm -f k9s_Linux_amd64.tar.gz
  SHELL
end
